### ISSUE TITLE
Kodi Control

### ISSUE THREAD

**Issue by flipmoo** [martintamare/homebridge-kodi#1]
Hi There,

I'm looking for a way to start and stop Kodi on raspbarian trough Homekit (homebridge).
Can you tell me if you solution does this? And how i could install this?

Thank you.

**Comment by martintamare** [comment]
Hello !

I did not have time yet to investigate :)
But for your problem, I would look into a simple switch or light switch (their must be some code already existing), and change to code. That "seems" easy ^^
